training_path: ../../data/musdb18_wave
output_path: out
learning_rate_0: 1.e-4
learning_rate_1: 1.e-5
validation_proportion: 0.1
validation_epochs_frequency: 1
training_epochs: 70
sampling_rate: 22050
batch_size_0: 16
batch_size_1: 32
batches_report: 160
snippets_per_audio_file: 100
output_size: 16384
down_kernel_size: 15
up_kernel_size: 5
depth: 12
num_filters: 24
device: cuda
